name: Auto Deploy to aws ec2

on: 
  push:
  pull_request:
    branches:
      - main


jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
    - name: pull request
    run: git pull

    - name: install dependencies
    run: npm i

    - name: run app
    run: npm run start



